// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// update_FTPRLCensoredRegression_matrix
void update_FTPRLCensoredRegression_matrix(NumericMatrix Rm, NumericVector y, LogicalVector is_observed, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLCensoredRegression_matrix(SEXP RmSEXP, SEXP ySEXP, SEXP is_observedSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type is_observed(is_observedSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLCensoredRegression_matrix(Rm, y, is_observed, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLCensoredRegression_dgCMatrix
void update_FTPRLCensoredRegression_dgCMatrix(S4 Rm, NumericVector y, LogicalVector is_observed, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLCensoredRegression_dgCMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP is_observedSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type is_observed(is_observedSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLCensoredRegression_dgCMatrix(Rm, y, is_observed, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLCensoredRegression_CSRMatrix
void update_FTPRLCensoredRegression_CSRMatrix(S4 Rm, NumericVector y, LogicalVector is_observed, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLCensoredRegression_CSRMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP is_observedSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type is_observed(is_observedSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLCensoredRegression_CSRMatrix(Rm, y, is_observed, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// predict_FTPRLCensoredRegression_matrix
SEXP predict_FTPRLCensoredRegression_matrix(NumericMatrix Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLCensoredRegression_matrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLCensoredRegression_matrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLCensoredRegression_dgCMatrix
SEXP predict_FTPRLCensoredRegression_dgCMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLCensoredRegression_dgCMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLCensoredRegression_dgCMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLCensoredRegression_CSRMatrix
SEXP predict_FTPRLCensoredRegression_CSRMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLCensoredRegression_CSRMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLCensoredRegression_CSRMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// update_FTPRLLinearRegression_matrix
void update_FTPRLLinearRegression_matrix(NumericMatrix Rm, NumericVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLLinearRegression_matrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLLinearRegression_matrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLLinearRegression_dgCMatrix
void update_FTPRLLinearRegression_dgCMatrix(S4 Rm, NumericVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLLinearRegression_dgCMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLLinearRegression_dgCMatrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLLinearRegression_CSRMatrix
void update_FTPRLLinearRegression_CSRMatrix(S4 Rm, NumericVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLLinearRegression_CSRMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLLinearRegression_CSRMatrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// predict_FTPRLLinearRegression_matrix
SEXP predict_FTPRLLinearRegression_matrix(NumericMatrix Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLLinearRegression_matrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLLinearRegression_matrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLLinearRegression_dgCMatrix
SEXP predict_FTPRLLinearRegression_dgCMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLLinearRegression_dgCMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLLinearRegression_dgCMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLLinearRegression_CSRMatrix
SEXP predict_FTPRLLinearRegression_CSRMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLLinearRegression_CSRMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLLinearRegression_CSRMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// update_FTPRLLogisticRegression_matrix
void update_FTPRLLogisticRegression_matrix(NumericMatrix Rm, LogicalVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLLogisticRegression_matrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLLogisticRegression_matrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLLogisticRegression_dgCMatrix
void update_FTPRLLogisticRegression_dgCMatrix(S4 Rm, LogicalVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLLogisticRegression_dgCMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLLogisticRegression_dgCMatrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLLogisticRegression_CSRMatrix
void update_FTPRLLogisticRegression_CSRMatrix(S4 Rm, LogicalVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLLogisticRegression_CSRMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLLogisticRegression_CSRMatrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// predict_FTPRLLogisticRegression_matrix
SEXP predict_FTPRLLogisticRegression_matrix(NumericMatrix Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLLogisticRegression_matrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLLogisticRegression_matrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLLogisticRegression_dgCMatrix
SEXP predict_FTPRLLogisticRegression_dgCMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLLogisticRegression_dgCMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLLogisticRegression_dgCMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLLogisticRegression_CSRMatrix
SEXP predict_FTPRLLogisticRegression_CSRMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLLogisticRegression_CSRMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLLogisticRegression_CSRMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// update_FTPRLNeuronNetwork_matrix
void update_FTPRLNeuronNetwork_matrix(NumericMatrix Rm, LogicalVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLNeuronNetwork_matrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLNeuronNetwork_matrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLNeuronNetwork_dgCMatrix
void update_FTPRLNeuronNetwork_dgCMatrix(S4 Rm, LogicalVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLNeuronNetwork_dgCMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLNeuronNetwork_dgCMatrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// update_FTPRLNeuronNetwork_CSRMatrix
void update_FTPRLNeuronNetwork_CSRMatrix(S4 Rm, LogicalVector y, S4 Rlearner);
RcppExport SEXP BridgewellML_update_FTPRLNeuronNetwork_CSRMatrix(SEXP RmSEXP, SEXP ySEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        update_FTPRLNeuronNetwork_CSRMatrix(Rm, y, Rlearner);
    }
    return R_NilValue;
END_RCPP
}
// predict_FTPRLNeuronNetwork_matrix
SEXP predict_FTPRLNeuronNetwork_matrix(NumericMatrix Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLNeuronNetwork_matrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLNeuronNetwork_matrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLNeuronNetwork_dgCMatrix
SEXP predict_FTPRLNeuronNetwork_dgCMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLNeuronNetwork_dgCMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLNeuronNetwork_dgCMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// predict_FTPRLNeuronNetwork_CSRMatrix
SEXP predict_FTPRLNeuronNetwork_CSRMatrix(S4 Rm, S4 Rlearner);
RcppExport SEXP BridgewellML_predict_FTPRLNeuronNetwork_CSRMatrix(SEXP RmSEXP, SEXP RlearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< S4 >::type Rlearner(RlearnerSEXP );
        SEXP __result = predict_FTPRLNeuronNetwork_CSRMatrix(Rm, Rlearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// get_w
SEXP get_w(S4 RLearner);
RcppExport SEXP BridgewellML_get_w(SEXP RLearnerSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type RLearner(RLearnerSEXP );
        SEXP __result = get_w(RLearner);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
