# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
update_FTPRLLinearRegression.matrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLLinearRegression_matrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
update_FTPRLLinearRegression.dgCMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLLinearRegression_dgCMatrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
update_FTPRLLinearRegression.CSRMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLLinearRegression_CSRMatrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
predict_FTPRLLinearRegression.matrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLLinearRegression_matrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
predict_FTPRLLinearRegression.dgCMatrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLLinearRegression_dgCMatrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
predict_FTPRLLinearRegression.CSRMatrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLLinearRegression_CSRMatrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
update_FTPRLLogisticRegression.matrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLLogisticRegression_matrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
update_FTPRLLogisticRegression.dgCMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLLogisticRegression_dgCMatrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
update_FTPRLLogisticRegression.CSRMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLLogisticRegression_CSRMatrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
predict_FTPRLLogisticRegression.matrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLLogisticRegression_matrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
predict_FTPRLLogisticRegression.dgCMatrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLLogisticRegression_dgCMatrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
predict_FTPRLLogisticRegression.CSRMatrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLLogisticRegression_CSRMatrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
update_FTPRLNeuronNetwork.matrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLNeuronNetwork_matrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
update_FTPRLNeuronNetwork.dgCMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLNeuronNetwork_dgCMatrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
update_FTPRLNeuronNetwork.CSRMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('BridgewellML_update_FTPRLNeuronNetwork_CSRMatrix', PACKAGE = 'BridgewellML', Rm, y, Rlearner))
}

#'@export
predict_FTPRLNeuronNetwork.matrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLNeuronNetwork_matrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
predict_FTPRLNeuronNetwork.dgCMatrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLNeuronNetwork_dgCMatrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

#'@export
predict_FTPRLNeuronNetwork.CSRMatrix <- function(Rm, Rlearner) {
    .Call('BridgewellML_predict_FTPRLNeuronNetwork_CSRMatrix', PACKAGE = 'BridgewellML', Rm, Rlearner)
}

