# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
update_FTPRLLogisticRegression.matrix <- function(Rm, y, Rlearner) {
    invisible(.Call('FTPRL_update_FTPRLLogisticRegression_matrix', PACKAGE = 'FTPRL', Rm, y, Rlearner))
}

#'@export
update_FTPRLLogisticRegression.dgCMatrix <- function(Rm, y, Rlearner) {
    invisible(.Call('FTPRL_update_FTPRLLogisticRegression_dgCMatrix', PACKAGE = 'FTPRL', Rm, y, Rlearner))
}

#'@export
predict_FTPRLLogisticRegression.matrix <- function(Rm, Rlearner) {
    .Call('FTPRL_predict_FTPRLLogisticRegression_matrix', PACKAGE = 'FTPRL', Rm, Rlearner)
}

#'@export
predict_FTPRLLogisticRegression.dgCMatrix <- function(Rm, Rlearner) {
    .Call('FTPRL_predict_FTPRLLogisticRegression_dgCMatrix', PACKAGE = 'FTPRL', Rm, Rlearner)
}

